/**
 * C4 Model Diagram Generator
 * Generates C4 model diagrams using Structurizr DSL format
 * @module generators/c4
 */

import { ArchitectureAnalysis, ArchitectureLayer } from '../types';

export interface C4Options {
  /** System name */
  systemName?: string;
  /** System description */
  systemDescription?: string;
  /** Include external systems */
  includeExternal?: boolean;
}

/**
 * Generate C4 Context diagram in Structurizr DSL format
 */
export function generateC4Context(
  analysis: ArchitectureAnalysis,
  options: C4Options = {}
): string {
  const {
    systemName = 'System',
    systemDescription = 'Architecture generated by ArchPulse',
  } = options;

  const lines: string[] = [];

  lines.push('workspace {');
  lines.push('  model {');
  lines.push(`    user = person "User" "A user of the system"`);
  lines.push('');

  // Main system
  lines.push(`    ${toId(systemName)} = softwareSystem "${systemName}" "${systemDescription}" {`);

  // Add containers for each layer
  for (const layer of analysis.layers) {
    const containerId = toId(layer.name);
    lines.push(`      ${containerId} = container "${layer.name}" "Layer: ${layer.name}" {`);

    // Add components for each module in layer
    for (const modulePath of layer.modules) {
      const node = analysis.graph.nodes.get(modulePath);
      if (node) {
        const componentId = toId(modulePath);
        const componentName = modulePath.split('/').pop()?.replace(/\.[^/.]+$/, '') || modulePath;
        lines.push(`        ${componentId} = component "${componentName}" "Module"`);
      }
    }

    lines.push('      }');
  }

  lines.push('    }');
  lines.push('');

  // Relationships
  lines.push('    # Relationships');
  lines.push(`    user -> ${toId(systemName)} "Uses"`);

  // Add inter-layer relationships
  const layerIds = analysis.layers.map(l => toId(l.name));
  for (let i = 0; i < layerIds.length - 1; i++) {
    lines.push(`    ${toId(systemName)}.${layerIds[i]} -> ${toId(systemName)}.${layerIds[i + 1]} "Depends on"`);
  }

  lines.push('  }');
  lines.push('');

  // Views
  lines.push('  views {');
  lines.push(`    systemContext ${toId(systemName)} "SystemContext" {`);
  lines.push('      include *');
  lines.push('      autoLayout');
  lines.push('    }');
  lines.push('');
  lines.push(`    container ${toId(systemName)} "Containers" {`);
  lines.push('      include *');
  lines.push('      autoLayout');
  lines.push('    }');
  lines.push('');

  // Component views for each container
  for (const layer of analysis.layers) {
    const containerId = toId(layer.name);
    lines.push(`    component ${toId(systemName)}.${containerId} "Components_${containerId}" {`);
    lines.push('      include *');
    lines.push('      autoLayout');
    lines.push('    }');
    lines.push('');
  }

  // Styles
  lines.push('    styles {');
  lines.push('      element "Person" {');
  lines.push('        shape Person');
  lines.push('        background #08427b');
  lines.push('        color #ffffff');
  lines.push('      }');
  lines.push('      element "Software System" {');
  lines.push('        background #1168bd');
  lines.push('        color #ffffff');
  lines.push('      }');
  lines.push('      element "Container" {');
  lines.push('        background #438dd5');
  lines.push('        color #ffffff');
  lines.push('      }');
  lines.push('      element "Component" {');
  lines.push('        background #85bbf0');
  lines.push('        color #000000');
  lines.push('      }');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate C4 diagram in PlantUML C4 format
 */
export function generateC4PlantUML(
  analysis: ArchitectureAnalysis,
  options: C4Options = {}
): string {
  const {
    systemName = 'System',
    systemDescription = 'Architecture generated by ArchPulse',
  } = options;

  const lines: string[] = [];

  lines.push('@startuml C4_Context');
  lines.push("!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml");
  lines.push("!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml");
  lines.push('');
  lines.push('LAYOUT_WITH_LEGEND()');
  lines.push('');
  lines.push('title C4 Context Diagram - ' + systemName);
  lines.push('');

  // Person
  lines.push('Person(user, "User", "A user of the system")');
  lines.push('');

  // System
  lines.push(`System_Boundary(${toId(systemName)}, "${systemName}") {`);

  // Containers for each layer
  for (const layer of analysis.layers) {
    const color = getLayerColor(layer);
    lines.push(`  Container(${toId(layer.name)}, "${layer.name}", "Layer", "${layer.modules.length} modules", "${color}")`);
  }

  lines.push('}');
  lines.push('');

  // Relationships
  lines.push('Rel(user, ' + toId(analysis.layers[0]?.name || 'system') + ', "Uses")');

  // Inter-layer relationships
  for (let i = 0; i < analysis.layers.length - 1; i++) {
    const from = toId(analysis.layers[i].name);
    const to = toId(analysis.layers[i + 1].name);
    lines.push(`Rel(${from}, ${to}, "Depends on")`);
  }

  lines.push('');
  lines.push('@enduml');

  return lines.join('\n');
}

/**
 * Generate C4 Component diagram in Mermaid C4 format
 */
export function generateC4Mermaid(
  analysis: ArchitectureAnalysis,
  options: C4Options = {}
): string {
  const { systemName = 'System' } = options;

  const lines: string[] = [];

  lines.push('C4Context');
  lines.push(`  title C4 Context Diagram - ${systemName}`);
  lines.push('');
  lines.push('  Person(user, "User", "A user of the system")');
  lines.push('');
  lines.push(`  System_Boundary(b0, "${systemName}") {`);

  for (const layer of analysis.layers) {
    lines.push(`    Container(${toId(layer.name)}, "${layer.name}", "Layer", "${layer.modules.length} modules")`);
  }

  lines.push('  }');
  lines.push('');

  // Relationships
  if (analysis.layers.length > 0) {
    lines.push(`  Rel(user, ${toId(analysis.layers[0].name)}, "Uses")`);
  }

  for (let i = 0; i < analysis.layers.length - 1; i++) {
    const from = toId(analysis.layers[i].name);
    const to = toId(analysis.layers[i + 1].name);
    lines.push(`  Rel(${from}, ${to}, "Depends on")`);
  }

  return lines.join('\n');
}

/**
 * Convert string to valid identifier
 */
function toId(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

/**
 * Get color for layer
 */
function getLayerColor(layer: ArchitectureLayer): string {
  const name = layer.name.toLowerCase();
  if (name.includes('api') || name.includes('controller')) return '#438dd5';
  if (name.includes('service')) return '#85bbf0';
  if (name.includes('data') || name.includes('model') || name.includes('db')) return '#9b59b6';
  if (name.includes('shared') || name.includes('util')) return '#95a5a6';
  return '#1168bd';
}
